apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sidecar
spec:
  gateways:
    - nginx-gateway
  hosts:
    - nginx-basic
  http:
    - match:
        - uri:
            prefix: /mn
      route:
        - destination:
            host: nginx-basic
            port:
              number: 80