apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sidecar
spec:
  hosts:
    - nginx-basic
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: nginx-basic
            port:
              number: 80